### ISSUE TITLE
was trying to steal your rasterizer xD 

### ISSUE THREAD

**Issue by olesgedz** [TebaHa/coolFDF#1]
Wth you are doing in calc_normal

vec1 = create_vector(&(t2), &(t0));
vec2 = create_vector(&(t1), &(t0));
[...]
free(vec1)
free(vec2)
use malloc every time is too slow .---.

**Comment by TebaHa** [comment]
Fixed!
Know i have a struct for polygon with buffered memory for vec3
```
typedef struct				s_fdf_poly
{
	t_point					p0;
	t_point					p1;
	t_point					p2;
	t_fdf_vec3				normal;
	int						color;
}							t_fdf_poly;
```

**Comment by olesgedz** [comment]
Ok, but actually my rtv1 works 10 times faster if I send vectors into function as a parameter and not a pointer to it, so keep it in mind
